### ISSUE TITLE
missing desktop entry after install

### ISSUE THREAD

**Issue by freddii** [qarkai/xautoclick#1]
to fix it i run:

cat << EOF | tee /home/$USER/.local/share/applications/xautoclick.desktop
[Desktop Entry]
Name=xautoclick
Comment=autoclicker for linux
Exec=gautoclick2
Icon=$HOME/programs_setup/xautoclick/mouse-pointer.svg
Terminal=false
Type=Application
Categories=System;Utility;Application;
EOF

but maybe that can be added to the program.

**Comment by qarkai** [comment]
> Icon=/home/xxUserxx/programs_setup/xautoclick/mouse-pointer.svg

What is mouse-pointer.svg?

**Comment by freddii** [comment]
its just a random opensource icon i choosed myself for that application:
https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/svg/mouse-pointer.svg

or to see it on github as icon:
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/mouse-pointer.svg

**Comment by freddii** [comment]
i am using this install script on debian
https://github.com/freddii/program_installers/blob/master/install_xautoclick.sh
