### ISSUE TITLE
Can't open config file ~/.config/xautoclick/config: No such file or directory

### ISSUE THREAD

**Issue by TheBlackKoala** [qarkai/xautoclick#13]
Running arch i had installed xautoclick from the repos i couldn't execute things, it just gave me the above error. I have now installed directly from the git-repo and when i use qt5autoclick i still get the exact same error.

**Comment by qarkai** [comment]
That should happen only at first launch. xautoclick creates config file at exit. Do you kill qt5autoclick using Ctrl+C?

**Comment by TheBlackKoala** [comment]
Yeah i see - it just continuously happened with cautoclick (which wouldn't work). Thanks for the help

**Comment by qarkai** [comment]
I'll try to add creating config file for ascii and cli GUIs.
