### ISSUE TITLE
Интегрировать иконку в favicon приложения.

### ISSUE THREAD

**Issue by don-rumata** [qarkai/xautoclick#4]
В панели задач отображается пустая белая заглушка - некрасиво.

**Comment by qarkai** [comment]
fltkAutoClick пока останется без иконки. FLTK 1.3 не поддерживает svg, а добавлять png пока не планирую.

**Comment by don-rumata** [comment]
Нахрен растр, если есть вектор. Ок :-(

**Comment by qarkai** [comment]
Выглядит примерно так:
![image](https://user-images.githubusercontent.com/9332266/80310895-90833580-87e5-11ea-9a62-ee50532d8396.png)

**Comment by don-rumata** [comment]
Это с вектором?
