### ISSUE TITLE
New option suggestion / help

### ISSUE THREAD

**Issue by oopmarcos** [qarkai/xautoclick#8]
Hello,

I would like the auto clicker to be active WHILE the mouse button is pressed (this is: auto click enabled while I maintain the mouse button pressed, stops when I let go, and starts again whenever I decide to hold down right-click). I don't have much programming experience, so I don't know how to do it. Could you please help me?

Thanks a lot

**Comment by qarkai** [comment]
Hi, I doubt it is doable. You have to watch for mouse events while creating them. I mean it could be hard or even impossible to distinct real click from auto. I haven't researched it thoroughly though and could be wrong.
You can start with examples of mouse clicks handling in libevdev.
